// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PostInput struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type UserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}
